#pragma once


#define SETTING_GAME_MISSION FName(TEXT("GAMEMISSION"))
#define SETTING_REGION FName(TEXT("REGION"))
#define SETTING_FACTION_PREFIX FName(TEXT("FACTION_"))
#define SETTING_FACTIONS FName(TEXT("FACTIONS"))
#define SETTING_GAME_VERSION FName(TEXT("GAMEVERSION"))
#define SETTING_CURRENT_PLAYER_AMOUNT FName(TEXT("CURRENTPLAYERAMOUNT"))
#define SETTING_STARTED_TIME FName(TEXT("MATCHSTARTEDTIME"))
#define SETTING_USER_DISPLAY_NAME FName(TEXT("USERDISPLAYNAME"))
#define SETTING_WEATHER_NAME FName(TEXT("WEATHER"))
#define SETTING_DAYTIME_NAME FName(TEXT("DAYTIME"))
#define SETTING_IN_GAME_UNIQUE_ID_FOR_SEARCH FName(TEXT("INGAMEUNIQUEIDFORSEARCH"))

#define DEFAULT_SESSION_NAME FName(TEXT("DEFAULT_SESSION_NAME"))
#define PARTY_LOBBY_SESSION_NAME FName(TEXT("PARTY_SESSION"))
